Broker = {
	GoalAngle = 0,
	GoalMagnitude = 127,
	ShowEffectiveAngles = false,
	SelectedItem = "Disabled",
	TargetStrain = false,
	Always = false,
	Left = true,
	Right = false,
	DYaw = false,
	DistanceMeasurement = false,
	DistanceMeasurementSaved = 0,
	DistAxisX = 0,
	DistAxisY = 0,
	DistAxisZ = 0,
	IgnoreY = false,
	Swimming = false,
}
