Settings = {
	goalAngle = 0,
	goalMag = 127,
	ShowEffectiveAngles = false,
	SelectedItem = "Disabled",
	TargetStrain = false,
	Always = false,
	Left = true,
	Right = false,
	DYaw = false,
	DistAxisX = false,
	DistAxisY = false,
	DistAxisZ = false,
	IgnoreY = false,
	Swimming = false,
}
