
Appearance = {
    Themes = {
        Classic = {
            WINDOW_BACK_COLOR = "#F0F0F0",
            BUTTON_BORDER_COLOR = "#B0B0B0",
            BUTTON_BACK_COLOR = "#E1E1E1",
            BUTTON_FORE_COLOR = "#000000",
            BUTTON_HOVERED_BORDER_COLOR = "#0078D7",
            BUTTON_HOVERED_BACK_COLOR = "#E5F1FB",
            BUTTON_PUSHED_BACK_COLOR = "#C5E1F7",
            TEXTBOX_BACK_COLOR = "#FFFFFF",
            TEXTBOX_READONLY_BACK_COLOR = "#F0F0F0",
            TEXTBOX_BORDER_COLOR = "#7A7A7A",
            TEXTBOX_HOVERED_BORDER_COLOR = "#171717",
            TEXTBOX_ACTIVE_BORDER_COLOR = "#0078D7",
            TEXTBOX_READONLY_FORE_COLOR = "#6D6D6D",
            SLIDER_TRACK_COLOR = "#E7EAEA",
            SLIDER_HEAD_COLOR = "#0078D7",
            SLIDER_PRESSED_HEAD_COLOR = "#CCCCCC",
            SLIDER_HOVERED_HEAD_COLOR = "#171717",
            JOYSTICK_LINE_COLOR = "#0000E5",
            JOYSTICK_TIP_COLOR = "#E50000", 
            LABEL_FORE_COLOR = "#000000",
            TOGGLEBUTTON_UNCHECKED_FORE_COLOR = "#000000",
            TOGGLEBUTTON_CHECKED_FORE_COLOR = "#000000",
            JOYSTICK_TIP_SIZE = 8,
            SLIDER_HEAD_WIDTH = 8,
            SLIDER_HEAD_HEIGHT = 16,
            SLIDER_TRACK_HEIGHT = 2,
            SLIDER_TRACK_WIDTH = 2,
            CARROUSEL_BUTTON_CHEVRON_WIDTH = 21,
            CARROUSEL_BUTTON_CHEVRON_HEIGHT = 21,
            CARROUSEL_BUTTON_CHEVRON_MARGIN = 10,
            FONT_SIZE = 10,
            FONT_NAME = "Segoe UI",
            BORDER_SIZE = 1,
        },
        Dark = {
            WINDOW_BACK_COLOR = "#202020",
            BUTTON_BORDER_COLOR = "#B0B0B0",
            BUTTON_BACK_COLOR = "#292929",
            BUTTON_FORE_COLOR = "#FFFFFF",
            BUTTON_HOVERED_BORDER_COLOR = "#0078D7",
            BUTTON_PUSHED_BACK_COLOR = "#4A4A4A",
            TEXTBOX_BACK_COLOR = "#111111",
            TEXTBOX_READONLY_BACK_COLOR = "#292929",
            TEXTBOX_BORDER_COLOR = "#7A7A7A",
            TEXTBOX_HOVERED_BORDER_COLOR = "#171717",
            TEXTBOX_ACTIVE_BORDER_COLOR = "#0078D7",
            TEXTBOX_READONLY_FORE_COLOR = "#6D6D6D",
            SLIDER_TRACK_COLOR = "#E7EAEA",
            SLIDER_HEAD_COLOR = "#0078D7",
            SLIDER_PRESSED_HEAD_COLOR = "#CCCCCC",
            SLIDER_HOVERED_HEAD_COLOR = "#171717",
            JOYSTICK_LINE_COLOR = "#00FF08",
            JOYSTICK_TIP_COLOR = "#FF0000",
            LABEL_FORE_COLOR = "#FFFFFF",
            TOGGLEBUTTON_UNCHECKED_FORE_COLOR = "#FFFFFF",
            TOGGLEBUTTON_CHECKED_FORE_COLOR = "#FFFFFF",
            JOYSTICK_TIP_SIZE = 8,
            SLIDER_HEAD_WIDTH = 8,
            SLIDER_HEAD_HEIGHT = 16,
            SLIDER_TRACK_HEIGHT = 2,
            SLIDER_TRACK_WIDTH = 2,
            CARROUSEL_BUTTON_CHEVRON_WIDTH = 21,
            CARROUSEL_BUTTON_CHEVRON_HEIGHT = 21,
            CARROUSEL_BUTTON_CHEVRON_MARGIN = 10,
            FONT_SIZE = 10,
            FONT_NAME = "Segoe UI",
            BORDER_SIZE = 1,
        },
        DarkFlat = {
            WINDOW_BACK_COLOR = "#202020",
            BUTTON_BORDER_COLOR = "#292929",
            BUTTON_BACK_COLOR = "#292929",
            BUTTON_FORE_COLOR = "#FFFFFF",
            BUTTON_HOVERED_BORDER_COLOR = "#0078D7",
            BUTTON_PUSHED_BACK_COLOR = "#4A4A4A",
            TEXTBOX_BACK_COLOR = "#111111",
            TEXTBOX_READONLY_BACK_COLOR = "#292929",
            TEXTBOX_BORDER_COLOR = "#111111",
            TEXTBOX_HOVERED_BORDER_COLOR = "#171717",
            TEXTBOX_ACTIVE_BORDER_COLOR = "#0078D7",
            TEXTBOX_READONLY_FORE_COLOR = "#6D6D6D",
            SLIDER_TRACK_COLOR = "#E7EAEA",
            SLIDER_HEAD_COLOR = "#0078D7",
            SLIDER_PRESSED_HEAD_COLOR = "#CCCCCC",
            SLIDER_HOVERED_HEAD_COLOR = "#171717",
            JOYSTICK_LINE_COLOR = "#00FF08",
            JOYSTICK_TIP_COLOR = "#FF0000",
            LABEL_FORE_COLOR = "#FFFFFF",
            TOGGLEBUTTON_UNCHECKED_FORE_COLOR = "#FFFFFF",
            TOGGLEBUTTON_CHECKED_FORE_COLOR = "#FFFFFF",
            JOYSTICK_TIP_SIZE = 8,
            SLIDER_HEAD_WIDTH = 8,
            SLIDER_HEAD_HEIGHT = 16,
            SLIDER_TRACK_HEIGHT = 2,
            SLIDER_TRACK_WIDTH = 2,
            CARROUSEL_BUTTON_CHEVRON_WIDTH = 21,
            CARROUSEL_BUTTON_CHEVRON_HEIGHT = 21,
            CARROUSEL_BUTTON_CHEVRON_MARGIN = 10,
            FONT_SIZE = 10,
            FONT_NAME = "Segoe UI",
            BORDER_SIZE = 1,
        },
        Inverted = {
            -- Autogenerated
        },
    },
    CurrentTheme = "Classic"
}



VERTICAL_SAFE_ZONE = 30
HORIZONTAL_SAFE_ZONE = 5


function Appearance.GetThemeNames()
    local names = {}
    for k, v in pairs(Appearance.Themes) do
        names[#names + 1] = k
    end
    return names
end

function Appearance.SetTheme(theme)
    if not Appearance.Themes[theme] then
        print("The theme \"" .. theme .. "\" was invalid and not applied")
        return
    end
    Appearance.CurrentTheme = theme
    --Appearance.Themes[CurrentTheme].FONT_SIZE = math.floor(Appearance.Themes[CurrentTheme].FONT_SIZE * ((Screen.Dimensions.ScalingX+Screen.Dimensions.ScalingY)/2))
end

function Appearance.Initialize()

    Appearance.Themes.Inverted = Table.DeepCopy(Appearance.Themes.Classic)

    for k, v in pairs(Appearance.Themes.Inverted) do
        if k:find("COLOR") then
            local rgb = CurrentRenderer:HexadecimalColorToRGB(Appearance.Themes.Inverted[k]);
            rgb[1] = 255 - rgb[1]
            rgb[2] = 255 - rgb[2]
            rgb[3] = 255 - rgb[3]
            Appearance.Themes.Inverted[k] = CurrentRenderer:RGBToHexadecimalColor(rgb)
        end
    end

    Appearance.SetTheme("Classic")
end


