
WINDOW_BACK_COLOR = "#F0F0F0"

BORDER_SIZE = 1

FONT_SIZE = 10

BUTTON_BORDER_COLOR = "#B0B0B0"
BUTTON_BACK_COLOR = "#E1E1E1"
BUTTON_FORE_COLOR = "#000000"
BUTTON_HOVERED_BORDER_COLOR = "#0078D7"
BUTTON_PUSHED_BACK_COLOR = "#C5E1F7"

TEXTBOX_BACK_COLOR = "#FFFFFF"
TEXTBOX_READONLY_BACK_COLOR = "#F0F0F0"
TEXTBOX_BORDER_COLOR = "#7A7A7A"
TEXTBOX_HOVERED_BORDER_COLOR = "#171717"
TEXTBOX_ACTIVE_BORDER_COLOR = BUTTON_HOVERED_BORDER_COLOR

SLIDER_TRACK_COLOR = "#E7EAEA"
SLIDER_HEAD_COLOR = BUTTON_HOVERED_BORDER_COLOR
SLIDER_PRESSED_HEAD_COLOR = "#CCCCCC"
SLIDER_HOVERED_HEAD_COLOR = TEXTBOX_HOVERED_BORDER_COLOR
SLIDER_HEAD_WIDTH = 8
SLIDER_HEAD_HEIGHT = SLIDER_HEAD_WIDTH * 2
SLIDER_TRACK_HEIGHT = 2

VERTICAL_SAFE_ZONE = 30